// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(OfficeDbContext))]
    [Migration("20220615084854_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Data.Entity.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            DepartmentName = "Java"
                        },
                        new
                        {
                            DepartmentId = 2,
                            DepartmentName = ".Net"
                        },
                        new
                        {
                            DepartmentId = 3,
                            DepartmentName = "Python"
                        },
                        new
                        {
                            DepartmentId = 4,
                            DepartmentName = "QA"
                        },
                        new
                        {
                            DepartmentId = 5,
                            DepartmentName = "HR"
                        },
                        new
                        {
                            DepartmentId = 6,
                            DepartmentName = "Marketing"
                        });
                });

            modelBuilder.Entity("Data.Entity.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataOfBirthday")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            DataOfBirthday = new DateTime(1994, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 5,
                            FirstName = "Alis",
                            Gender = 2,
                            LastName = "Roud"
                        },
                        new
                        {
                            EmployeeId = 2,
                            DataOfBirthday = new DateTime(1979, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            FirstName = "Jhon",
                            Gender = 1,
                            LastName = "Ready"
                        },
                        new
                        {
                            EmployeeId = 3,
                            DataOfBirthday = new DateTime(1998, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            FirstName = "Alex",
                            Gender = 1,
                            LastName = "Leus"
                        },
                        new
                        {
                            EmployeeId = 4,
                            DataOfBirthday = new DateTime(1996, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            FirstName = "Nikol",
                            Gender = 2,
                            LastName = "Zeus"
                        },
                        new
                        {
                            EmployeeId = 5,
                            DataOfBirthday = new DateTime(1994, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            FirstName = "Dima",
                            Gender = 1,
                            LastName = "Mykulenko"
                        },
                        new
                        {
                            EmployeeId = 6,
                            DataOfBirthday = new DateTime(1991, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            FirstName = "Sergey",
                            Gender = 1,
                            LastName = "Reva"
                        },
                        new
                        {
                            EmployeeId = 7,
                            DataOfBirthday = new DateTime(1990, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 4,
                            FirstName = "Olena",
                            Gender = 2,
                            LastName = "Ivanova"
                        },
                        new
                        {
                            EmployeeId = 8,
                            DataOfBirthday = new DateTime(1999, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 5,
                            FirstName = "Anastasiya",
                            Gender = 2,
                            LastName = "Reznik"
                        },
                        new
                        {
                            EmployeeId = 9,
                            DataOfBirthday = new DateTime(1996, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 4,
                            FirstName = "Bogdan",
                            Gender = 1,
                            LastName = "Bogdanovich"
                        });
                });

            modelBuilder.Entity("Data.Entity.Employee", b =>
                {
                    b.HasOne("Data.Entity.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });
#pragma warning restore 612, 618
        }
    }
}
